name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Startup Nebula
        run: |
          cd ./.nebula-up
          rm -rf ./data ./log
          docker-compose up
          sleep 20
          ./console.sh -f /root/init.ngql
          cd ..

      - name: build
        run: |
          npm install --unsafe-perm
          npm run build

      - name: test
        run: |
          npm run test
      
      - name: query
        run: |
          cd ./.nebula-up
          ./console.sh -e "show spaces"
          docker-compose down
          cd ..