name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: show env
        run: |
          export

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare env
        run: |
          pwd
          ls -alh

      - name: docker compose info
        run: |
          docker-compose -v

      - name: docker info 
        run: |
          docker info