name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Startup Nebula
        run: |
          cd ./.nebula-up
          docker-compose up -d
          cd ..

      - name: build
        run: |
          npm install --verbose --unsafe-perm
          npm run build

      - name: test
        run: |
          npm run test