name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Show ENV
        run: |
          export
          echo $PWD
          docker -v
          docker-compose -v

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Startup Nebula
        run: |
          cd ./.nebula-up
          rm -rf ./data ./log
          docker-compose up -d
          echo "Sleep 20s for waiting nebula cluster"
          sleep 20
          ./check.sh
          echo "Create space nebula_node"
          ./console.sh -e "create space nebula_node(vid_type = FIXED_STRING(30));"
          echo "Sleep 5s for waiting `space` ready"
          sleep 5
          ./console.sh -f /root/init-create.ngql
          echo "Sleep 20s for `schema` ready"
          sleep 20
          ./console.sh -f /root/init-data.ngql
          cd ..
 
      - name: Query
        run: |
          cd ./.nebula-up
          ls -alh
          ./console.sh -e "show spaces"
          docker-compose down
          cd ..